### ISSUE TITLE
Is there a way to configure the host IP address?

### ISSUE THREAD

**Issue by davidgoate** [arakelian/docker-junit-rule#1]
Given the following code:

```java
import com.arakelian.docker.junit.DockerRule;
import com.arakelian.docker.junit.model.HostConfigurer;
import com.arakelian.docker.junit.model.ImmutableDockerConfig;
import com.arakelian.docker.junit.model.StartedListener;
import com.spotify.docker.client.messages.PortBinding;
import lombok.RequiredArgsConstructor;

import java.util.concurrent.TimeUnit;

import static java.util.Collections.singletonList;
import static java.util.Collections.singletonMap;

class DynamoDockerRule extends DockerRule {
    private static final String DOCKER_IMAGE = "dwmkerr/dynamodb:38";
    private static final String DYNAMO_PORT_IN_CONTAINER = "8000";
    private static final String CONTAINER_NAME_PREFIX = "dynamo-test-";

    DynamoDockerRule(final String hostAddress, final int hostPortNumber) {
        super(ImmutableDockerConfig.builder()
                .name(CONTAINER_NAME_PREFIX + hostPortNumber)
                .image(DOCKER_IMAGE)
                .ports(DYNAMO_PORT_IN_CONTAINER)
                .addContainerConfigurer(c -> c.cmd("-inMemory"))
                .alwaysRemoveContainer(true)
                .addHostConfigurer(configureDockerHost(hostAddress, hostPortNumber))
                .addStartedListener(waitForPortToRespond(hostPortNumber))
                .build());
    }

    private static HostConfigurer configureDockerHost(final String hostAddress, final int hostPortNumber) {
        return host -> {
            final LocalPortBinding binding = new LocalPortBinding(hostAddress, Integer.toString(hostPortNumber));
            host.portBindings(singletonMap(DYNAMO_PORT_IN_CONTAINER, singletonList(binding)));
        };
    }

    private static StartedListener waitForPortToRespond(final int hostPortNumber) {
        return container -> container.waitForPort(hostPortNumber, 15, TimeUnit.SECONDS);
    }

    @RequiredArgsConstructor
    private static final class LocalPortBinding extends PortBinding {

        private final String hostIp;
        private final String hostPort;

        @Override
        public String hostIp() {
            return hostIp;
        }

        @Override
        public String hostPort() {
            return hostPort;
        }
    }
}
```

When I pass the arguments hostAddress=172.29.1.18 and hostPortNumber=7466

My container is successfully started and a `docker ps` yields:

```bash
172.29.1.18:7466->8000/tcp   dynamo-test-7466
```

Notice that I don't bind to `0.0.0.0` and opt to bind to `172.29.1.18` which came from `InetAddress.getLocalHost().getHostAddress()`.

The issue is that on the line of code:

```java
 container.waitForPort(hostPortNumber, 15, TimeUnit.SECONDS);
```

my test fails and times out with  `INFO com.arakelian.docker.junit.DockerRule - Waiting for container at localhost:7466`

Notice that it expecting to connect to `localhost` rather than `172.29.1.18`. I can't pass my host as an argument to the `waitForPort` method, which seems to use some local state internally called `host`.  My question is can I set this value or is there another way to do this?

## Why Are You Even Trying This?
* I wanted a standard way of running this container across environments.
* When explicitly binding to `127.0.00.1` or `localhost` (e.g. `localhost:7466->8000/tcp` or `127.0.0.1:7466->8000/tcp`) on some environments the waitForPort failed because it seemed to want to reach a different IP, e.g. 172.xxx.xxx.xxx instead.

## Why Not Just Bind To 0.0.0.0
* I think this fixes my issues, but it seems like more that I need, I don't need anything outside of this host to connect to this container during tests.

## Current Workaround
I have two workarounds right now, either work:

1) bind to 0.0.0.0
2) copy and paste the method `com.arakelian.docker.junit.Container#waitForPort(int, int, java.util.concurrent.TimeUnit)` into my own class which allows me to also supply a `host` String (where i pass the `hostAddress` variable).

**Comment by arakelian** [comment]
Thanks for the detailed bug report.  I've added a method Container#waitForPort(String, int, int, TimeUnit), but I'm also going to fix the code that detect the host/ip.  Should be resolved by tomorrow.

**Comment by arakelian** [comment]
Resolved by commit 6a4002c3b0b0fcebfb070abc57a8f2c4c109b638

**Comment by arakelian** [comment]
You should be able to use container.waitForPort("8000/tcp", 15, TimeUnit.SECONDS).  The new method fetches both the host name / port number from the Docker network settings.

**Comment by davidgoate** [comment]
@arakelian thanks for this, updated  and tested and it works really well!
